export const cityReadTitle="/Definition/City/ReadTitle"

export const CityCreate="/Definition/City/Create"
export const CityRead="/Definition/City/Read"
export const CityReadPaging="/Definition/City/ReadPaging"
export const CityGetOneRecord="/Definition/City/GetOneRecord"
export const CityDelete="/Definition/City/Delete"
export const CityUpdate="/Definition/City/Update"
export const CityFavorite="/Definition/City/SetToFavorite"
export const CityExportId="/Definition/City/ExportId"
export const CityExport="/Definition/City/Export"
export const CitySampleFile="/Definition/City/SampleFile"
export const CityCheckFile="/Definition/City/CheckFile"
export const CityImportFile="/Definition/City/Import"
export const CityLog="/Definition/City/Log"
export const CitySetUnselectedColumn="/Definition/City/SetUnselectedColumn"
export const CityAccessList="/Definition/City/AccessList"