export const customerCreate = "/Customer/Customer/Create"
export const customerRead="/Customer/Customer/Read"
export const customerReadPaging="/Customer/Customer/ReadPaging"
export const customerGetOneRecord="/Customer/Customer/GetOneRecord"
export const customerDelete="/Customer/Customer/Delete"
export const customerUpdate="/Customer/Customer/Update"
export const customerFavorite="/Customer/Customer/SetToFavorite"
export const customerExportId="/Customer/Customer/ExportId"
export const customerExport="/Customer/Customer/Export"
export const customerSampleFile="/Customer/Customer/SampleFile"
export const customerCheckFile="/Customer/Customer/CheckFile"
export const customerImportFile="/Customer/Customer/Import"
export const customerLog="/Customer/Customer/Log"
export const customerSetUnselectedColumn="/Customer/Customer/SetUnselectedColumn"
export const customerAccessList="/Customer/Customer/AccessList"
export const customerChangePassword="/Customer/Customer/ChangePassword"
export const customerCreateAddress="/Customer/Customer/CreateAddress"
export const customerReadAddress="/Customer/Customer/ReadAddress"
export const customerUpdateAddress="/Customer/Customer/UpdateAddress"
export const customerDeleteAddress="/Customer/Customer/DeleteAddress"

export const customerCreateMobile="/Customer/Customer/CreateMobile"
export const customerReadMobile="/Customer/Customer/ReadMobile"
export const customerUpdateMobile="/Customer/Customer/UpdateMobile"
export const customerDeleteMobile="/Customer/Customer/DeleteMobile"

export const customerCreateBankAccount="/Customer/Customer/CreateBankAccount"
export const customerReadBankAccount="/Customer/Customer/ReadBankAccount"
export const customerUpdateBankAccount="/Customer/Customer/UpdateBankAccount"
export const customerDeleteBankAccount="/Customer/Customer/DeleteBankAccount"

export const customerCreatePhone="/Customer/Customer/CreatePhone"
export const customerReadPhone="/Customer/Customer/ReadPhone"
export const customerUpdatePhone="/Customer/Customer/UpdatePhone"
export const customerDeletePhone="/Customer/Customer/DeletePhone"
export const CustomerColumnInfo='/Customer/Customer/ColumnInfo'
export const CustomerImportArray='/Customer/Customer/ImportArray'