export const groupRead="/Operator/Group/Read"
export const groupReadPaging="/Operator/Group/ReadPaging"
export const groupGetOneRecord="/Operator/Group/GetOneRecord"
export const groupDelete="/Operator/Group/Delete"
export const groupUpdate="/Operator/Group/Update"
export const groupFavorite="/Operator/Group/SetToFavorite"
export const groupExport="/Operator/Group/Export"