export const groupRead="/Operator/Group/Read"
export const groupReadTitle="/Operator/Group/ReadTitle"
export const groupCreate="/Operator/Group/Create"
export const groupReadPaging="/Operator/Group/ReadPaging"
export const groupGetOneRecord="/Operator/Group/GetOneRecord"
export const groupDelete="/Operator/Group/Delete"
export const groupUpdate="/Operator/Group/Update"
export const groupFavorite="/Operator/Group/SetToFavorite"
export const groupExportId="/Operator/Group/ExportId"
export const groupExport="/Operator/Group/Export"
export const groupSampleFile="/Operator/Group/SampleFile"
export const groupCheckFile="/Operator/Group/CheckFile"
export const groupImportFile="/Operator/Group/Import"
export const groupLog="/Operator/Group/Log"
export const groupSetUnselectedColumn="/Operator/Group/SetUnselectedColumn"
export const groupAccessList="/Operator/Group/AccessList"
export const groupGetPermission="/Operator/Group/GetPermission"
export const groupSetPermission="/Operator/Group/SetPermission"
export const groupCreatePolicyBrowser="/Operator/Group/CreatePolicyBrowser"
export const groupReadPolicyBrowser="/Operator/Group/ReadPolicyBrowser"
export const groupUpdatePolicyBrowser="/Operator/Group/UpdatePolicyBrowser"
export const groupDeletePolicyBrowser="/Operator/Group/DeletePolicyBrowser"

export const groupCreatePolicyIP="/Operator/Group/CreatePolicyIP"
export const groupReadPolicyIP="/Operator/Group/ReadPolicyIP"
export const groupUpdatePolicyIP="/Operator/Group/UpdatePolicyIP"
export const groupDeletePolicyIP="/Operator/Group/DeletePolicyIP"


export const groupCreatePolicyOs="/Operator/Group/CreatePolicyOs"
export const groupReadPolicyOs="/Operator/Group/ReadPolicyOs"
export const groupUpdatePolicyOs="/Operator/Group/UpdatePolicyOs"
export const groupDeletePolicyOs="/Operator/Group/DeletePolicyOs"

export const groupCreatePolicyLocation="/Operator/Group/CreatePolicyLocation"
export const groupReadPolicyLocation="/Operator/Group/ReadPolicyLocation"
export const groupUpdatePolicyLocation="/Operator/Group/UpdatePolicyLocation"
export const groupDeletePolicyLocation="/Operator/Group/DeletePolicyLocation"
export const groupColumnInfo='/Operator/Group/ColumnInfo'
export const groupImportArray='/Operator/Group/ImportArray'