export const productGroupCreate="/Definition/ProductGroup/Create"
export const productGroupReadTitle="/Definition/ProductGroup/ReadTitle"

export const productGroupRead="/Definition/ProductGroup/Read"
export const productGroupReadPaging="/Definition/ProductGroup/ReadPaging"
export const productGroupGetOneRecord="/Definition/ProductGroup/GetOneRecord"
export const productGroupDelete="/Definition/ProductGroup/Delete"
export const productGroupUpdate="/Definition/ProductGroup/Update"
export const productGroupFavorite="/Definition/ProductGroup/SetToFavorite"
export const productGroupExportId="/Definition/ProductGroup/ExportId"
export const productGroupExport="/Definition/ProductGroup/Export"
export const productGroupSampleFile="/Definition/ProductGroup/SampleFile"
export const productGroupCheckFile="/Definition/ProductGroup/CheckFile"
export const productGroupImportFile="/Definition/ProductGroup/Import"
export const productGroupLog="/Definition/ProductGroup/Log"
export const productGroupSetUnselectedColumn="/Definition/ProductGroup/SetUnselectedColumn"
export const productGroupAccessList="/Definition/ProductGroup/AccessList"