
export const technicianCreate="/Definition/Technician/Create"
export const technicianRead="/Definition/Technician/Read"
export const technicianReadPaging="/Definition/Technician/ReadPaging"
export const technicianGetOneRecord="/Definition/Technician/GetOneRecord"
export const technicianDelete="/Definition/Technician/Delete"
export const technicianUpdate="/Definition/Technician/Update"
export const technicianFavorite="/Definition/Technician/SetToFavorite"
export const technicianExportId="/Definition/Technician/ExportId"
export const technicianExport="/Definition/Technician/Export"
export const technicianSampleFile="/Definition/Technician/SampleFile"
export const technicianCheckFile="/Definition/Technician/CheckFile"
export const technicianImportFile="/Definition/Technician/Import"
export const technicianLog="/Definition/Technician/Log"
export const technicianSetUnselectedColumn="/Definition/Technician/SetUnselectedColumn"
export const technicianAccessList="/Definition/Technician/AccessList"