
export const VehicleTypeCreate="/Definition/VehicleType/Create"
export const VehicleTypeRead="/Definition/VehicleType/Read"
export const VehicleTypeReadPaging="/Definition/VehicleType/ReadPaging"
export const VehicleTypeGetOneRecord="/Definition/VehicleType/GetOneRecord"
export const VehicleTypeDelete="/Definition/VehicleType/Delete"
export const VehicleTypeUpdate="/Definition/VehicleType/Update"
export const VehicleTypeFavorite="/Definition/VehicleType/SetToFavorite"
export const VehicleTypeExportId="/Definition/VehicleType/ExportId"
export const VehicleTypeExport="/Definition/VehicleType/Export"
export const VehicleTypeSampleFile="/Definition/VehicleType/SampleFile"
export const VehicleTypeCheckFile="/Definition/VehicleType/CheckFile"
export const VehicleTypeImportFile="/Definition/VehicleType/Import"
export const VehicleTypeLog="/Definition/VehicleType/Log"
export const VehicleTypeSetUnselectedColumn="/Definition/VehicleType/SetUnselectedColumn"
export const VehicleTypeAccessList="/Definition/VehicleType/AccessList"